server:
  port: 8080
jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 1440m
spring:
  application:
    name: todo-test
#  datasource:
#    url: jdbc:postgresql://localhost:5432/todos
#    username: postgres
#    password: dv9899
#    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    show-sql: true
  sql:
    init:
      platform: postgres
      mode: embedded
  docker:
    compose:
      enabled: true
      lifecycle-management: start_and_stop