server:
  port: 8080
jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 10m
spring:
  application:
    name: todo-test
  datasource:
    url: jdbc:postgresql://localhost:5432/todos    # jdbc:h2:mem:testtask  jdbc:h2:file:./users;MODE=PostgreSQL
    username: postgres    # sa
    password: dv9899     # password
    driver-class-name: org.postgresql.Driver      # org.h2.Driver
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    database-platform=: org.hibernate.dialect.PostgreSQLDialect  # org.hibernate.dialect.H2Dialect
    database: POSTGRESQL
    show-sql: true
  sql:
    init:
      platform: postgres
  flyway:
    baseline-on-migrate: true
# swagger-ui custom path
#springdoc:
#    swagger-ui:
#      path: /swagger-ui/index.html